In [78]:
import pandas as pd 
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler ,LabelEncoder
import pickle

In [79]:
import sys
!{sys.executable} -m pip install scikit-learn

Requirement already satisfied: scikit-learn in c:\users\mihik\appdata\local\programs\python\python311\lib\site-packages (1.9.0)
Requirement already satisfied: numpy>=1.24.1 in c:\users\mihik\appdata\local\programs\python\python311\lib\site-packages (from scikit-learn) (2.4.6)
Requirement already satisfied: scipy>=1.10.0 in c:\users\mihik\appdata\local\programs\python\python311\lib\site-packages (from scikit-learn) (1.16.3)
Requirement already satisfied: joblib>=1.4.0 in c:\users\mihik\appdata\local\programs\python\python311\lib\site-packages (from scikit-learn) (1.5.3)
Requirement already satisfied: narwhals>=2.0.1 in c:\users\mihik\appdata\local\programs\python\python311\lib\site-packages (from scikit-learn) (2.14.0)
Requirement already satisfied: threadpoolctl>=3.5.0 in c:\users\mihik\appdata\local\programs\python\python311\lib\site-packages (from scikit-learn) (3.6.0)

[notice] A new release of pip is available: 24.0 -> 26.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [80]:
import sklearn
print(sklearn.__version__)

1.9.0

In [81]:
## load the dataset
data=pd.read_csv("Churn_Modelling.csv")
data.head()

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0

In [82]:
## preprocess the data
### drp irrelevant columns
data =data.drop(['RowNumber','CustomerId','Surname'],axis=1)
data

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0
...,...,...,...,...,...,...,...,...,...,...,...
9995,771,France,Male,39,5,0.00,2,1,0,96270.64,0
9996,516,France,Male,35,10,57369.61,1,1,1,101699.77,0
9997,709,France,Female,36,7,0.00,1,0,1,42085.58,1
9998,772,Germany,Male,42,3,75075.31,2,1,0,92888.52,1
9999,792,France,Female,28,4,130142.79,1,1,0,38190.78,0

In [83]:
## encoder categorical variable
label_encoder_gender=LabelEncoder()
data['Gender']=label_encoder_gender.fit_transform(data['Gender'])
data

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,619,France,0,42,2,0.00,1,1,1,101348.88,1
1,608,Spain,0,41,1,83807.86,1,0,1,112542.58,0
2,502,France,0,42,8,159660.80,3,1,0,113931.57,1
3,699,France,0,39,1,0.00,2,0,0,93826.63,0
4,850,Spain,0,43,2,125510.82,1,1,1,79084.10,0
...,...,...,...,...,...,...,...,...,...,...,...
9995,771,France,1,39,5,0.00,2,1,0,96270.64,0
9996,516,France,1,35,10,57369.61,1,1,1,101699.77,0
9997,709,France,0,36,7,0.00,1,0,1,42085.58,1
9998,772,Germany,1,42,3,75075.31,2,1,0,92888.52,1
9999,792,France,0,28,4,130142.79,1,1,0,38190.78,0

In [84]:
## onehotencoder
from sklearn.preprocessing import OneHotEncoder
onehot_encoder_geo=OneHotEncoder( )
geo_encoder=onehot_encoder_geo.fit_transform(data[['Geography']])
geo_encoder

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 10000 stored elements and shape (10000, 3)>

In [85]:
onehot_encoder_geo.get_feature_names_out(['Geography'])

array(['Geography_France', 'Geography_Germany', 'Geography_Spain'],
      dtype=object)

In [86]:
geo_encoded_df = pd.DataFrame(
    geo_encoder.toarray(),
    columns=onehot_encoder_geo.get_feature_names_out(['Geography'])
)

In [87]:
geo_encoder.toarray()

array([[1., 0., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       ...,
       [1., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.]])

In [88]:
geo_encoded_df = pd.DataFrame(geo_encoder.toarray(),
    columns=onehot_encoder_geo.get_feature_names_out(['Geography'])
)
geo_encoded_df

      Geography_France  Geography_Germany  Geography_Spain
0                  1.0                0.0              0.0
1                  0.0                0.0              1.0
2                  1.0                0.0              0.0
3                  1.0                0.0              0.0
4                  0.0                0.0              1.0
...                ...                ...              ...
9995               1.0                0.0              0.0
9996               1.0                0.0              0.0
9997               1.0                0.0              0.0
9998               0.0                1.0              0.0
9999               1.0                0.0              0.0

[10000 rows x 3 columns]

In [89]:
## combine one hot encoder columns with the original data
data = pd.concat([data.drop('Geography',axis =1),geo_encoded_df],axis=1)
data.head()

,CreditScore,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited,Geography_France,Geography_Germany,Geography_Spain
0,619,0,42,2,0.00,1,1,1,101348.88,1,1.0,0.0,0.0
1,608,0,41,1,83807.86,1,0,1,112542.58,0,0.0,0.0,1.0
2,502,0,42,8,159660.80,3,1,0,113931.57,1,1.0,0.0,0.0
3,699,0,39,1,0.00,2,0,0,93826.63,0,1.0,0.0,0.0
4,850,0,43,2,125510.82,1,1,1,79084.10,0,0.0,0.0,1.0

In [90]:
## save the encoder and  scaler
with open('label_encoder_gender.pkl','wb') as file:
    pickle.dump(label_encoder_gender,file)

with open('onehot_encoder_geo.pkl','wb') as file:
    pickle.dump(onehot_encoder_geo,file)

In [91]:
## divide the dataset into indepentnt and dependent feature
x=data.drop('Exited',axis=1)
y=data['Exited']

## split the data in training and testing sets
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2,random_state=42)

## scale these features
scaler = StandardScaler()
x_train=scaler.fit_transform(x_train)
x_test=scaler.transform(x_test)

In [103]:
x_train

array([[ 0.35649971,  0.91324755, -0.6557859 , ...,  1.00150113,
        -0.57946723, -0.57638802],
       [-0.20389777,  0.91324755,  0.29493847, ..., -0.99850112,
         1.72572313, -0.57638802],
       [-0.96147213,  0.91324755, -1.41636539, ..., -0.99850112,
        -0.57946723,  1.73494238],
       ...,
       [ 0.86500853, -1.09499335, -0.08535128, ...,  1.00150113,
        -0.57946723, -0.57638802],
       [ 0.15932282,  0.91324755,  0.3900109 , ...,  1.00150113,
        -0.57946723, -0.57638802],
       [ 0.47065475,  0.91324755,  1.15059039, ..., -0.99850112,
         1.72572313, -0.57638802]])

In [93]:
with open('scaler.pkl','wb') as file:
    pickle.dump(scaler,file)

In [94]:
data

,CreditScore,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited,Geography_France,Geography_Germany,Geography_Spain
0,619,0,42,2,0.00,1,1,1,101348.88,1,1.0,0.0,0.0
1,608,0,41,1,83807.86,1,0,1,112542.58,0,0.0,0.0,1.0
2,502,0,42,8,159660.80,3,1,0,113931.57,1,1.0,0.0,0.0
3,699,0,39,1,0.00,2,0,0,93826.63,0,1.0,0.0,0.0
4,850,0,43,2,125510.82,1,1,1,79084.10,0,0.0,0.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,771,1,39,5,0.00,2,1,0,96270.64,0,1.0,0.0,0.0
9996,516,1,35,10,57369.61,1,1,1,101699.77,0,1.0,0.0,0.0
9997,709,0,36,7,0.00,1,0,1,42085.58,1,1.0,0.0,0.0
9998,772,1,42,3,75075.31,2,1,0,92888.52,1,0.0,1.0,0.0
9999,792,0,28,4,130142.79,1,1,0,38190.78,0,1.0,0.0,0.0

In [95]:
###ANN IMPLEMENTION

In [96]:
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.callbacks import EarlyStopping,TensorBoard
import datetime

In [97]:
import tensorflow as tf
print(tf.__version__)

2.21.0

In [98]:
import sys
print(sys.executable)

c:\Users\mihik\AppData\Local\Programs\Python\Python311\python.exe

In [99]:
!{sys.executable} -m pip show tensorflow

Name: tensorflow
Version: 2.21.0
Summary: TensorFlow is an open source machine learning framework for everyone.
Home-page: https://www.tensorflow.org/
Author: Google Inc.
Author-email: packages@tensorflow.org
License: Apache 2.0
Location: c:\Users\mihik\AppData\Local\Programs\Python\Python311\Lib\site-packages
Requires: absl-py, astunparse, flatbuffers, gast, google_pasta, grpcio, h5py, keras, libclang, ml_dtypes, numpy, opt_einsum, packaging, protobuf, requests, setuptools, six, termcolor, typing_extensions, wrapt
Required-by:

In [100]:
!{sys.executable} -m pip install tensorflow

Requirement already satisfied: tensorflow in c:\users\mihik\appdata\local\programs\python\python311\lib\site-packages (2.21.0)
Requirement already satisfied: absl-py>=1.0.0 in c:\users\mihik\appdata\local\programs\python\python311\lib\site-packages (from tensorflow) (2.5.0)
Requirement already satisfied: astunparse>=1.6.0 in c:\users\mihik\appdata\local\programs\python\python311\lib\site-packages (from tensorflow) (1.6.3)
Requirement already satisfied: flatbuffers>=25.9.23 in c:\users\mihik\appdata\local\programs\python\python311\lib\site-packages (from tensorflow) (25.12.19)
Requirement already satisfied: gast!=0.5.0,!=0.5.1,!=0.5.2,>=0.2.1 in c:\users\mihik\appdata\local\programs\python\python311\lib\site-packages (from tensorflow) (0.7.0)
Requirement already satisfied: google_pasta>=0.1.1 in c:\users\mihik\appdata\local\programs\python\python311\lib\site-packages (from tensorflow) (0.2.0)
Requirement already satisfied: libclang>=13.0.0 in c:\users\mihik\appdata\local\programs\python\python311\lib\site-packages (from tensorflow) (18.1.1)
Requirement already satisfied: opt_einsum>=2.3.2 in c:\users\mihik\appdata\local\programs\python\python311\lib\site-packages (from tensorflow) (3.4.0)
Requirement already satisfied: packaging in c:\users\mihik\appdata\local\programs\python\python311\lib\site-packages (from tensorflow) (26.3)
Requirement already satisfied: protobuf<8.0.0,>=6.31.1 in c:\users\mihik\appdata\local\programs\python\python311\lib\site-packages (from tensorflow) (7.35.1)
Requirement already satisfied: requests<3,>=2.21.0 in c:\users\mihik\appdata\local\programs\python\python311\lib\site-packages (from tensorflow) (2.32.5)
Requirement already satisfied: setuptools in c:\users\mihik\appdata\local\programs\python\python311\lib\site-packages (from tensorflow) (65.5.0)
Requirement already satisfied: six>=1.12.0 in c:\users\mihik\appdata\local\programs\python\python311\lib\site-packages (from tensorflow) (1.17.0)
Requirement already satisfied: termcolor>=1.1.0 in c:\users\mihik\appdata\local\programs\python\python311\lib\site-packages (from tensorflow) (3.3.0)
Requirement already satisfied: typing_extensions>=3.6.6 in c:\users\mihik\appdata\local\programs\python\python311\lib\site-packages (from tensorflow) (4.15.0)
Requirement already satisfied: wrapt>=1.11.0 in c:\users\mihik\appdata\local\programs\python\python311\lib\site-packages (from tensorflow) (2.3.0)
Requirement already satisfied: grpcio<2.0,>=1.24.3 in c:\users\mihik\appdata\local\programs\python\python311\lib\site-packages (from tensorflow) (1.83.0)
Requirement already satisfied: keras>=3.12.0 in c:\users\mihik\appdata\local\programs\python\python311\lib\site-packages (from tensorflow) (3.15.1)
Requirement already satisfied: numpy>=1.26.0 in c:\users\mihik\appdata\local\programs\python\python311\lib\site-packages (from tensorflow) (2.4.6)
Requirement already satisfied: h5py<3.15.0,>=3.11.0 in c:\users\mihik\appdata\local\programs\python\python311\lib\site-packages (from tensorflow) (3.14.0)
Requirement already satisfied: ml_dtypes<1.0.0,>=0.5.1 in c:\users\mihik\appdata\local\programs\python\python311\lib\site-packages (from tensorflow) (0.6.0)
Requirement already satisfied: wheel<1.0,>=0.23.0 in c:\users\mihik\appdata\local\programs\python\python311\lib\site-packages (from astunparse>=1.6.0->tensorflow) (0.48.0)
Requirement already satisfied: rich in c:\users\mihik\appdata\local\programs\python\python311\lib\site-packages (from keras>=3.12.0->tensorflow) (13.9.4)
Requirement already satisfied: namex in c:\users\mihik\appdata\local\programs\python\python311\lib\site-packages (from keras>=3.12.0->tensorflow) (0.1.0)
Requirement already satisfied: optree in c:\users\mihik\appdata\local\programs\python\python311\lib\site-packages (from keras>=3.12.0->tensorflow) (0.19.1)
Requirement already satisfied: charset_normalizer<4,>=2 in c:\users\mihik\appdata\local\programs\python\python311\lib\site-packages (from requests<3,>=2.21.0->tensorflow) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in c:\users\mihik\appdata\local\programs\python\python311\lib\site-packages (from requests<3,>=2.21.0->tensorflow) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\mihik\appdata\local\programs\python\python311\lib\site-packages (from requests<3,>=2.21.0->tensorflow) (1.26.6)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\mihik\appdata\local\programs\python\python311\lib\site-packages (from requests<3,>=2.21.0->tensorflow) (2025.11.12)
Requirement already satisfied: markdown-it-py>=2.2.0 in c:\users\mihik\appdata\local\programs\python\python311\lib\site-packages (from rich->keras>=3.12.0->tensorflow) (4.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in c:\users\mihik\appdata\local\programs\python\python311\lib\site-packages (from rich->keras>=3.12.0->tensorflow) (2.19.2)
Requirement already satisfied: mdurl~=0.1 in c:\users\mihik\appdata\local\programs\python\python311\lib\site-packages (from markdown-it-py>=2.2.0->rich->keras>=3.12.0->tensorflow) (0.1.2)

[notice] A new release of pip is available: 24.0 -> 26.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [105]:
(x_train.shape[1],)

(12,)

In [106]:
## build our ANN model
model=Sequential([
    Dense(64,activation='relu',input_shape=(x_train.shape[1],)),## hl1 connected with input layer
    Dense(32,activation='relu'),## hl2
    Dense(1,activation='sigmoid') ## output layer
])

c:\Users\mihik\AppData\Local\Programs\Python\Python311\Lib\site-packages\keras\src\layers\core\dense.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

In [107]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense (Dense)                   │ (None, 64)             │           832 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 32)             │         2,080 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_2 (Dense)                 │ (None, 1)              │            33 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 2,945 (11.50 KB)

 Trainable params: 2,945 (11.50 KB)

 Non-trainable params: 0 (0.00 B)

In [109]:
import tensorflow
opt=tensorflow.keras.optimizers.Adam(learning_rate=0.01)
loss=tensorflow.keras.losses.BinaryCrossentropy()
loss

In [111]:
## compile the model
model.compile(optimizer=opt ,loss="binary_crossentropy",metrics=['accuracy'])

WARNING:tensorflow:TensorFlow GPU support is not available on native Windows for TensorFlow >= 2.11. Even if CUDA/cuDNN are installed, GPU will not be used. Please use WSL2 or the TensorFlow-DirectML plugin.

In [117]:
## set up the tensorboard
from tensorflow.keras.callbacks import EarlyStopping,TensorBoard
log_dir="logs/fit" + datetime.datetime.now().strftime("%y%m%d-%H%M%S")
tensorflow_callback=TensorBoard(log_dir=log_dir,histogram_freq=1)

In [120]:
## set up Early stopping
early_stopping_callback=EarlyStopping(monitor='val_loss',patience=5,restore_best_weights=True)

In [126]:
## train the model
history=model.fit(
    x_train,y_train,validation_data=(x_test,y_test),epochs=100,
    callbacks=[tensorflow_callback,early_stopping_callback]
)

Epoch 1/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 3s 8ms/step - accuracy: 0.8344 - loss: 0.3972 - val_accuracy: 0.8570 - val_loss: 0.3497
Epoch 2/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.8554 - loss: 0.3545 - val_accuracy: 0.8540 - val_loss: 0.3548
Epoch 3/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8583 - loss: 0.3475 - val_accuracy: 0.8600 - val_loss: 0.3513
Epoch 4/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8583 - loss: 0.3449 - val_accuracy: 0.8570 - val_loss: 0.3555
Epoch 5/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8593 - loss: 0.3419 - val_accuracy: 0.8615 - val_loss: 0.3453
Epoch 6/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8625 - loss: 0.3403 - val_accuracy: 0.8615 - val_loss: 0.3491
Epoch 7/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8635 - loss: 0.3363 - val_accuracy: 0.8610 - val_loss: 0.3515
Epoch 8/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8634 - loss: 0.3359 - val_accuracy: 0.8585 - val_loss: 0.3454
Epoch 9/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.8641 - loss: 0.3329 - val_accuracy: 0.8595 - val_loss: 0.3438
Epoch 10/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8644 - loss: 0.3301 - val_accuracy: 0.8535 - val_loss: 0.3513
Epoch 11/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8631 - loss: 0.3290 - val_accuracy: 0.8610 - val_loss: 0.3417
Epoch 12/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8674 - loss: 0.3253 - val_accuracy: 0.8575 - val_loss: 0.3467
Epoch 13/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.8669 - loss: 0.3228 - val_accuracy: 0.8550 - val_loss: 0.3508
Epoch 14/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - accuracy: 0.8640 - loss: 0.3230 - val_accuracy: 0.8525 - val_loss: 0.3470
Epoch 15/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.8680 - loss: 0.3215 - val_accuracy: 0.8575 - val_loss: 0.3529
Epoch 16/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.8714 - loss: 0.3195 - val_accuracy: 0.8590 - val_loss: 0.3586

In [123]:
import tensorboard
print(tensorboard.__version__)

ModuleNotFoundError: No module named 'tensorboard'

In [124]:
!{sys.executable} -m pip install tensorboard

Collecting tensorboard
  Using cached tensorboard-2.21.0-py3-none-any.whl.metadata (1.8 kB)
Requirement already satisfied: absl-py>=0.4 in c:\users\mihik\appdata\local\programs\python\python311\lib\site-packages (from tensorboard) (2.5.0)
Requirement already satisfied: grpcio<2.0,>=1.74.0 in c:\users\mihik\appdata\local\programs\python\python311\lib\site-packages (from tensorboard) (1.83.0)
Collecting markdown>=2.6.8 (from tensorboard)
  Using cached markdown-3.10.3-py3-none-any.whl.metadata (5.1 kB)
Requirement already satisfied: numpy>=1.12.0 in c:\users\mihik\appdata\local\programs\python\python311\lib\site-packages (from tensorboard) (2.4.6)
Requirement already satisfied: packaging in c:\users\mihik\appdata\local\programs\python\python311\lib\site-packages (from tensorboard) (26.3)
Requirement already satisfied: pillow in c:\users\mihik\appdata\local\programs\python\python311\lib\site-packages (from tensorboard) (9.5.0)
Requirement already satisfied: protobuf<8.0.0,>=6.31.1 in c:\users\mihik\appdata\local\programs\python\python311\lib\site-packages (from tensorboard) (7.35.1)
Requirement already satisfied: setuptools>=41.0.0 in c:\users\mihik\appdata\local\programs\python\python311\lib\site-packages (from tensorboard) (65.5.0)
Collecting tensorboard-data-server<0.8.0,>=0.7.0 (from tensorboard)
  Using cached tensorboard_data_server-0.7.2-py3-none-any.whl.metadata (1.1 kB)
Requirement already satisfied: werkzeug>=1.0.1 in c:\users\mihik\appdata\local\programs\python\python311\lib\site-packages (from tensorboard) (3.1.4)
Requirement already satisfied: typing-extensions~=4.12 in c:\users\mihik\appdata\local\programs\python\python311\lib\site-packages (from grpcio<2.0,>=1.74.0->tensorboard) (4.15.0)
Requirement already satisfied: markupsafe>=2.1.1 in c:\users\mihik\appdata\local\programs\python\python311\lib\site-packages (from werkzeug>=1.0.1->tensorboard) (3.0.3)
Downloading tensorboard-2.21.0-py3-none-any.whl (5.5 MB)
   ---------------------------------------- 0.0/5.5 MB ? eta -:--:--
   ---------------------------------------- 0.0/5.5 MB ? eta -:--:--
   ---------------------------------------- 0.0/5.5 MB ? eta -:--:--
   ---------------------------------------- 0.0/5.5 MB ? eta -:--:--
   ---------------------------------------- 0.0/5.5 MB 131.3 kB/s eta 0:00:42
   ---------------------------------------- 0.1/5.5 MB 238.1 kB/s eta 0:00:23
    --------------------------------------- 0.1/5.5 MB 403.5 kB/s eta 0:00:14
   - -------------------------------------- 0.1/5.5 MB 532.5 kB/s eta 0:00:11
   - -------------------------------------- 0.2/5.5 MB 656.9 kB/s eta 0:00:09
   - -------------------------------------- 0.3/5.5 MB 714.4 kB/s eta 0:00:08
   -- ------------------------------------- 0.3/5.5 MB 827.2 kB/s eta 0:00:07
   -- ------------------------------------- 0.4/5.5 MB 890.4 kB/s eta 0:00:06
   --- ------------------------------------ 0.5/5.5 MB 973.2 kB/s eta 0:00:06
   ---- ----------------------------------- 0.6/5.5 MB 1.1 MB/s eta 0:00:05
   ---- ----------------------------------- 0.6/5.5 MB 1.1 MB/s eta 0:00:05
   ----- ---------------------------------- 0.7/5.5 MB 1.2 MB/s eta 0:00:05
   ----- ---------------------------------- 0.8/5.5 MB 1.2 MB/s eta 0:00:04
   ------ --------------------------------- 0.9/5.5 MB 1.3 MB/s eta 0:00:04
   ------- -------------------------------- 1.0/5.5 MB 1.3 MB/s eta 0:00:04
   -------- ------------------------------- 1.2/5.5 MB 1.4 MB/s eta 0:00:04
   --------- ------------------------------ 1.3/5.5 MB 1.4 MB/s eta 0:00:03
   ---------- ----------------------------- 1.4/5.5 MB 1.5 MB/s eta 0:00:03
   ---------- ----------------------------- 1.5/5.5 MB 1.5 MB/s eta 0:00:03
   ------------ --------------------------- 1.7/5.5 MB 1.6 MB/s eta 0:00:03
   ------------ --------------------------- 1.8/5.5 MB 1.7 MB/s eta 0:00:03
   ------------- -------------------------- 1.9/5.5 MB 1.7 MB/s eta 0:00:03
   ------------- -------------------------- 1.9/5.5 MB 1.7 MB/s eta 0:00:03
   --------------- ------------------------ 2.1/5.5 MB 1.7 MB/s eta 0:00:02
   --------------- ------------------------ 2.2/5.5 MB 1.8 MB/s eta 0:00:02
   ---------------- ----------------------- 2.3/5.5 MB 1.8 MB/s eta 0:00:02
   ----------------- ---------------------- 2.4/5.5 MB 1.8 MB/s eta 0:00:02
   ------------------ --------------------- 2.6/5.5 MB 1.8 MB/s eta 0:00:02
   ------------------- -------------------- 2.7/5.5 MB 1.9 MB/s eta 0:00:02
   -------------------- ------------------- 2.8/5.5 MB 1.9 MB/s eta 0:00:02
   -------------------- ------------------- 2.9/5.5 MB 1.9 MB/s eta 0:00:02
   --------------------- ------------------ 3.0/5.5 MB 1.9 MB/s eta 0:00:02
   ---------------------- ----------------- 3.1/5.5 MB 1.9 MB/s eta 0:00:02
   ---------------------- ----------------- 3.1/5.5 MB 1.9 MB/s eta 0:00:02
   ----------------------- ---------------- 3.3/5.5 MB 1.9 MB/s eta 0:00:02
   ----------------------- ---------------- 3.3/5.5 MB 1.9 MB/s eta 0:00:02
   ------------------------ --------------- 3.4/5.5 MB 1.9 MB/s eta 0:00:02
   ------------------------- -------------- 3.5/5.5 MB 1.9 MB/s eta 0:00:02
   -------------------------- ------------- 3.7/5.5 MB 1.9 MB/s eta 0:00:01
   --------------------------- ------------ 3.8/5.5 MB 1.9 MB/s eta 0:00:01
   ---------------------------- ----------- 3.9/5.5 MB 2.0 MB/s eta 0:00:01
   ----------------------------- ---------- 4.1/5.5 MB 2.0 MB/s eta 0:00:01
   ------------------------------ --------- 4.2/5.5 MB 2.0 MB/s eta 0:00:01
   -------------------------------- ------- 4.4/5.5 MB 2.1 MB/s eta 0:00:01
   --------------------------------- ------ 4.6/5.5 MB 2.1 MB/s eta 0:00:01
   ---------------------------------- ----- 4.8/5.5 MB 2.2 MB/s eta 0:00:01
   ------------------------------------ --- 5.0/5.5 MB 2.2 MB/s eta 0:00:01
   -------------------------------------- - 5.3/5.5 MB 2.3 MB/s eta 0:00:01
   ---------------------------------------  5.4/5.5 MB 2.3 MB/s eta 0:00:01
   ---------------------------------------- 5.5/5.5 MB 2.3 MB/s eta 0:00:00
Using cached markdown-3.10.3-py3-none-any.whl (110 kB)
Using cached tensorboard_data_server-0.7.2-py3-none-any.whl (2.4 kB)
Installing collected packages: tensorboard-data-server, markdown, tensorboard
Successfully installed markdown-3.10.3 tensorboard-2.21.0 tensorboard-data-server-0.7.2

[notice] A new release of pip is available: 24.0 -> 26.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [125]:
import sys
!{sys.executable} -m pip install tensorboard

Requirement already satisfied: tensorboard in c:\users\mihik\appdata\local\programs\python\python311\lib\site-packages (2.21.0)
Requirement already satisfied: absl-py>=0.4 in c:\users\mihik\appdata\local\programs\python\python311\lib\site-packages (from tensorboard) (2.5.0)
Requirement already satisfied: grpcio<2.0,>=1.74.0 in c:\users\mihik\appdata\local\programs\python\python311\lib\site-packages (from tensorboard) (1.83.0)
Requirement already satisfied: markdown>=2.6.8 in c:\users\mihik\appdata\local\programs\python\python311\lib\site-packages (from tensorboard) (3.10.3)
Requirement already satisfied: numpy>=1.12.0 in c:\users\mihik\appdata\local\programs\python\python311\lib\site-packages (from tensorboard) (2.4.6)
Requirement already satisfied: packaging in c:\users\mihik\appdata\local\programs\python\python311\lib\site-packages (from tensorboard) (26.3)
Requirement already satisfied: pillow in c:\users\mihik\appdata\local\programs\python\python311\lib\site-packages (from tensorboard) (9.5.0)
Requirement already satisfied: protobuf<8.0.0,>=6.31.1 in c:\users\mihik\appdata\local\programs\python\python311\lib\site-packages (from tensorboard) (7.35.1)
Requirement already satisfied: setuptools>=41.0.0 in c:\users\mihik\appdata\local\programs\python\python311\lib\site-packages (from tensorboard) (65.5.0)
Requirement already satisfied: tensorboard-data-server<0.8.0,>=0.7.0 in c:\users\mihik\appdata\local\programs\python\python311\lib\site-packages (from tensorboard) (0.7.2)
Requirement already satisfied: werkzeug>=1.0.1 in c:\users\mihik\appdata\local\programs\python\python311\lib\site-packages (from tensorboard) (3.1.4)
Requirement already satisfied: typing-extensions~=4.12 in c:\users\mihik\appdata\local\programs\python\python311\lib\site-packages (from grpcio<2.0,>=1.74.0->tensorboard) (4.15.0)
Requirement already satisfied: markupsafe>=2.1.1 in c:\users\mihik\appdata\local\programs\python\python311\lib\site-packages (from werkzeug>=1.0.1->tensorboard) (3.0.3)

[notice] A new release of pip is available: 24.0 -> 26.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [127]:
model.save('model.h5')

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

In [6]:
## load tensorboard extension
%load_ext tensorboard

In [11]:
%tensorboard --logdir  logs/fit260818-170317

Reusing TensorBoard on port 6007 (pid 14376), started 0:00:21 ago. (Use '!kill 14376' to kill it.)